name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        configuration: [Debug Release]
        compiler: [clang]

    steps:
    - name: Install compiler
      id: install_cc
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: clang-latest

    - name: Checkout repository
      # Checkout the repository to the GitHub Actions runner
      uses: actions/checkout@v3

    - name: Install dependencies
      # external libraries used by SFML Hack ?
      run: sudo apt-get update && sudo apt-get install -y build-essential mesa-common-dev libx11-dev libxrandr-dev libgl1-mesa-dev libglu1-mesa-dev libxi-dev libudev-dev libgl1-mesa-dev

    - name: Setup Vcpkg
      uses: friendlyanon/setup-vcpkg@v1
      with: 
        committish: 63aa65e65b9d2c08772ea15d25fb8fdb0d32e557

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: CMake Configure
      env:
        CC: ${{ steps.install_cc.outputs.cc }}
        CXX: ${{ steps.install_cc.outputs.cxx }}
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G "Unix Makefiles" -D "CMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE:STRING=${{ matrix.configuration }} -DCMAKE_CXX_COMPILER=${{env.CXX}} -DCMAKE_C_COMPILER=${{env.CC}}
    
    - name: CMake Build
      run: cmake --build ${{github.workspace}}/build

    - name: Unit Tests
      run: ctest --test-dir ${{github.workspace}}/build -VV
